    expect(renewalReminder).toContain('queueSingleSms');
    expect(renewalReminder).toContain("'admin.finance_service_renewal_reminder_sent'");
    expect(recordDetails).toContain("type === 'invoice'");
    expect(recordDetails).toContain("type === 'receipt'");
    expect(recordDetails).toContain("type === 'bill'");
    expect(recordDetails).toContain("type === 'expense'");
    expect(recordDetails).toContain('invoiceBalance(invoice.total, invoice.allocations, invoice.creditNotes)');
    expect(recordDetails).toContain('invoiceBalance(bill.total, bill.allocations)');
    expect(recordDetails).toContain("auditTrail('ClientInvoice'");
    expect(recordDetails).toContain("auditTrail('ClientPayment'");
    expect(recordDetails).toContain("auditTrail('FinanceVendorBill'");
    expect(recordDetails).toContain("auditTrail('FinanceExpense'");
    expect(financeDetails).toContain('Payment allocations');
    expect(financeDetails).toContain('Invoice allocations');
    expect(financeDetails).toContain('Related account activity');
    expect(financeDetails).toContain('Audit trail');
    expect(financeDetails).toContain('Record receipt');
    expect(financeDetails).toContain('Pay supplier');
    expect(financeDetails).toContain('max-w-6xl');
    expect(accounting).toContain('Chart of accounts');
    expect(accounting).toContain('Posted journals');
    expect(accounting).toContain('Trial balance');
    expect(accounting).toContain('General ledger');
    expect(accounting).toContain('lg:grid-cols-[minmax(280px,2fr)_minmax(150px,1fr)_minmax(150px,1fr)_120px_minmax(140px,auto)]');
    expect(accounting).toContain('lg:grid-cols-[160px_120px_minmax(130px,auto)]');
    expect(accounting).toContain('lg:items-end');
    expect(accounting).toContain('Accounting periods');
    expect(accounting).toContain('Prepare balanced journal');
    expect(accounting).toContain('Submit for approval');
    expect(accounting).toContain('independent checker');
    expect(accounting).toContain('Control difference');
    expect(accounting).toContain('Opening balance');
    expect(accounting).toContain('Closing balance');
    expect(accounting).toContain('Reverse posted journal?');
    expect(accounting).toContain('Post reversal');
    expect(accounting).toContain('Financial statements');
    expect(accounting).toContain('FinanceFinancialStatements');
    expect(cashbookWorkspace).toContain('lg:grid-cols-[150px_150px_110px_minmax(150px,170px)_minmax(140px,auto)]');
    expect(statementsWorkspace).toContain('lg:grid-cols-[160px_160px_120px_minmax(150px,auto)]');
    expect(taxWorkspace).toContain('lg:grid-cols-[160px_160px_110px_minmax(130px,auto)]');
    expect(accounting).toContain('Cashbook & treasury');
    expect(accounting).toContain('FinanceCashbookWorkspace');
    expect(accounting).toContain('FinanceLedgerInitialization');