import { describe, expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

function source(relativePath: string): string {
  return readFileSync(join(process.cwd(), relativePath), 'utf8');
}

describe('Search Console and indexing readiness', () => {
  test('admin SEO settings expose verification state and live crawl resources', () => {
    const settings = source('src/components/admin/AdminSettings.tsx');

    expect(settings).toContain('Search visibility readiness');
    expect(settings).toContain('https://search.google.com/search-console');
    expect(settings).toContain('Google verification');
    expect(settings).toContain('Bing verification');
    expect(settings).toContain("canonicalSiteUrl + '/sitemap.xml'");
    expect(settings).toContain("canonicalSiteUrl + '/robots.txt'");
    expect(settings).toContain("canonicalSiteUrl + '/services/software-development'");
    expect(settings).toContain("canonicalSiteUrl + '/services/it-training'");
  });

  test('verification workflow never fabricates a token', () => {
    const settings = source('src/components/admin/AdminSettings.tsx');
    const docs = source('docs/PRODUCTION.md');

    expect(settings).toContain('Verification tokens are never guessed or generated by the website.');
    expect(settings).toContain('paste only its');
    expect(settings).toContain('content');
    expect(docs).toContain('Never invent a token.');
    expect(docs).toContain('seo_google_verification');
  });

  test('operations guide treats Search Console as the indexing source of truth', () => {
    const docs = source('docs/PRODUCTION.md');

    expect(docs).toContain('https://lightworldtech.com/sitemap.xml');
    expect(docs).toContain('/services/software-development');
    expect(docs).toContain('/services/it-training');
    expect(docs).toContain('Search Console Performance and Pages reports');
    expect(docs).toContain('source of truth for queries, impressions, clicks, indexed URLs and crawl problems');
  });

  test('admin explains that crawlability is distinct from verified Search Console ownership', () => {
    const settings = source('src/components/admin/AdminSettings.tsx');

    expect(settings).toContain('The website is crawlable and indexable');
    expect(settings).toContain('Search Console ownership cannot be confirmed');
  });
});
