ALTER TABLE "ClientOrganization"
ADD COLUMN "paymentTermsDays" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN "creditLimitCurrency" TEXT NOT NULL DEFAULT 'GHS',
ADD COLUMN "creditLimit" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN "creditHold" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "creditHoldReason" TEXT NOT NULL DEFAULT '';
