ALTER TABLE "FinanceVendorBill"
ADD COLUMN "voidedByAdminId" TEXT NOT NULL DEFAULT '',
ADD COLUMN "voidedBy" TEXT NOT NULL DEFAULT '',
ADD COLUMN "voidedAt" TIMESTAMP(3),
ADD COLUMN "voidReason" TEXT NOT NULL DEFAULT '';
